apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booking-app
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: booking-frontend-service
            port:
              number: 80