apiVersion: v1
kind: Service
metadata:
  name: booking-frontend-service
spec:
  selector:
    app: booking-frontend
  ports:
    - protocol: {{ .Values.service.protocol | default "TCP" }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}